// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmblvuvsqczgwgriyhkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtYmx2dXZzcWN6Z3dncml5aGtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzMTI1NTksImV4cCI6MjA0OTg4ODU1OX0.heJjpNZXstu5jBR8d37k2sAjZVnq93A-m_c0Qdq8GUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);